version: '3.9'

services:
  discord_job_db:
    image: postgres:16.1
    container_name: discord_bot_job_postgres
    restart: always
    environment:
      - POSTGRES_USER=sonbao0901
      - POSTGRES_PASSWORD=thongminh01
      - POSTGRES_DB=discord_job_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data  # Use named volume

volumes:
  pg_data:
